---
- name: "Ansible Playbook"
  hosts: amazon
  become: true
  vars_files: 
    - main.vars
  tasks:
  
    - name: "Installing Apache"
      yum:
        name: "{{ packages}} "
        state: present

    - name: "creating httpd.conf from httpd.conf.tmpl"
      template:
        src: httpd.conf.tmpl
        dest: /etc/httpd/conf/httpd.conf
      
    - name: "Restarting/Enabling Apache"
      service:
        name: "{{ item }}"
        state: restarted
        enabled: true
      with_items: "{{ services }}"
