---
- name: "Ansible Playbook"
  hosts: amazon
  become: true
  vars_files: 
    - main.vars
  tasks:
  
    - name: "Installing Apache"
      yum:
        name: "{{ packages}} "
        state: present
    - name: "Installing php"
    - name: "creating php.ini from php.ini.tmpl"
    - name: "creating httpd.conf from httpd.conf.tmpl"
      template:
        src: httpd.conf.tmpl
        dest: /etc/httpd/conf/httpd.conf

    - name: "Creating Virtualhost Config File From Template"
      template:
        src: virtualhost.conf.tmpl
        dest: "/etc/httpd/conf.d/default.conf"
        owner: "{{ owner }}"
        group: "{{ group }}"

    - name: "creating documentroot for virtualhost"
      file: 
        path: /var/www/html/{{ httpd_domain }}
        state: directory
        owner: "{{ owner }}"
        group: "{{ group }}"

    - name: "Creating index.html"
      copy:
        content: "<h1><center> Virtual Host {{ ansible_fqdn }} </center></h1>"
        dest: "/var/www/html/{{ httpd_domain }}/index.html"
        owner: "{{ owner }}"
        group: "{{ group }}"    
      
    - name: "Restarting/Enabling Apache"
      service:
        name: "{{ item }}"
        state: restarted
        enabled: true
      with_items: "{{ services }}"

    - installing postgres
    - restarting/enabling postgres
    - creating database
    - creating user
